//
//  CGPointSwiftDocTests.swift
//  SOMETHING
//
//  Created by SOMEONE on SOMEWHEN.
//  Copyright (c) SOME STUFF. All rights reserved.
//

// *******************************************************************************************
// * These unit tests were automatically generated by: https://github.com/schwa/SwiftDocTest *
// *******************************************************************************************

import Cocoa
import XCTest

import SwiftGraphics

class CGPointSwiftDocTests: XCTestCase {
    func test_23126dc80bdd3fdb985aee0b2234ff3ec00ecab6() {
        let result = CGPoint(x:1, y:2) + CGPoint(x:10, y:20)
        let expected_result = CGPoint(x:11, y:22)
        XCTAssertEqual(result, expected_result)
    }
    func test_a9147ff57b6fc28170f2fd34010dcd805088553d() {
        let result = CGPoint(x:11, y:22) - CGPoint(x:10, y:20)
        let expected_result = CGPoint(x:1, y:2)
        XCTAssertEqual(result, expected_result)
    }
    func test_5ae06e9ba2b24c91d5e85550b59bae6a9beaa17b() {
        let result = CGPoint(x:0, y:0).isZero
        let expected_result = true
        XCTAssertEqual(result, expected_result)
    }
    func test_2ce3d4cb2d1f009553ca51dd2bf4982098687749() {
        let result = CGPoint(x:1, y:0).isZero
        let expected_result = false
        XCTAssertEqual(result, expected_result)
    }
    func test_b8a1a3cfeef1e64f1cfbd8a3252890e16d397200() {
        let result = CGPoint(x:50, y:50).clampedTo(CGRect(x:10, y:20, w:100, h:100))
        let expected_result = CGPoint(x:50, y:50)
        XCTAssertEqual(result, expected_result)
    }
    func test_0ccbe0a5a9a42bbbcf25eb107c1cf3d83a81dae9() {
        let result = CGPoint(x:150, y:50).clampedTo(CGRect(x:10, y:20, w:100, h:100))
        let expected_result = CGPoint(x:110, y:50)
        XCTAssertEqual(result, expected_result)
    }
    func test_e7bd44171946f518cafde41445ef0993c3782132() {
        let result = CGPoint(x:0, y:50).clampedTo(CGRect(x:10, y:20, w:100, h:100))
        let expected_result = CGPoint(x:10, y:50)
        XCTAssertEqual(result, expected_result)
    }
    func test_ed4f3f458ec7eb65cb43891e5fb41a5f9295b102() {
        let result = CGPoint(x:50, y:00).clampedTo(CGRect(x:10, y:20, w:100, h:100))
        let expected_result = CGPoint(x:50, y:20)
        XCTAssertEqual(result, expected_result)
    }
    func test_ba0a788729712c63dbc83cbf9ba39ef96f6a3746() {
        let result = floor(CGPoint(x:10.9, y:-10.5))
        let expected_result = CGPoint(x:10, y:-11)
        XCTAssertEqual(result, expected_result)
    }
    func test_c6cdf9945105f6f702b9d22d909d3c0c505ea2b7() {
        let result = ceil(CGPoint(x:10.9, y:-10.5))
        let expected_result = CGPoint(x:11, y:-10)
        XCTAssertEqual(result, expected_result)
    }
    func test_e71dd9bf7127b87065bf7412149f4c625ceecd68() {
        let result = round(CGPoint(x:10.9, y:-10.6))
        let expected_result = CGPoint(x:11, y:-11)
        XCTAssertEqual(result, expected_result)
    }
    func test_5097696df2ec6230b235df30db56741689018f69() {
        let result = floor(CGPoint(x:10.09, y:-10.95))
        let expected_result = CGPoint(x:10, y:-11)
        XCTAssertEqual(result, expected_result)
    }
}